### ISSUE TITLE
Newest Version

### ISSUE THREAD

**Issue by glatzert** [mudrd8mz/moodle-report_overviewstats#9]
Hi David and thanks for your work.

Do you think you could update the repository links to a maintained one?
Since Moodle promotes installing plugins via git, your module cannot be updated that way.

**Comment by mudrd8mz** [comment]
Hi @glatzert 

Sorry I am not sure I fully understand what you mean. The links at https://moodle.org/plugins/report_overviewstats should point here to this github and that holds the latest available version.

You should be aware that the plugin has been seeking for a new maintainer.

**Comment by glatzert** [comment]
I'm aware, of the maintainer situation, but currently confused nevertheless.

Moodle Plugin Directory states the latest version is of 2019.
This repository (at least publically) contains a single branch with the latest commit from 2015?

**Comment by mudrd8mz** [comment]
Ah, I see. Sorry about that and well spotted! 2015 was the last real code change. Since then, the only change (by the previous maintainer who had adopted this plugin but the adoption was cancelled recently) was marking the plugin as still compatible with recent Moodle versions and bumping the version number (which was one of the reasons why the adoption was cancelled).

I just added a commit to put the Git in sync with the ZIP version in the plugins directory.

Thank you for reporting this!

**Comment by glatzert** [comment]
Thank YOU for taking care :)

**Comment by mudrd8mz** [comment]
Heh, I wish I actually did. Any contributions / improvements will be appreciated here.
